{% set name = "karawun" %}
{% set version = "0.2.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/karawun-{{ version }}.tar.gz
  sha256: 0321538e614dcef8a54b36cd4cbb71b5b44434c039236cfc7c1f5bb6e166b4c9

build:
  number: 1
  noarch: python
  entry_points:
    - importTractography = karawun.commandline:import_tractography_cl
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.13.0
    - pydicom ==1.4.2
    - python >={{ python_min }},<3.10a0
    - simpleitk >=1.2.0,<=2.0.2

test:
  imports:
    - karawun
  commands:
    - pip check
    - importTractography --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/karawun/
  summary: DICOM image, segmgmentation image and fibre object converter
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/DevelopmentalImagingMCRI/karawun

extra:
  recipe-maintainers:
    - richardbeare
